"""
Processes the log files generated by tests (pruning, data structuring) and restores the source code.

Accepts absolute (or relative) paths for all input/output files.
Supports multiple target folders via a file or direct parameter, consistent with run-instrumentation-demo.ps1.
The input log file is expected to be already deduplicated (e.g., produced by the JUnit listener).

This module can be used both as a CLI script and as an imported function.
"""

import argparse
import os
import sys
import re
import subprocess
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent


def _sort_calltree_markdown(calltree_path, log_file, block_line_mapping_file, block_signature_file):
    if not os.path.isfile(calltree_path):
        print(f"[INFO] Calltree file not found for sorting: {calltree_path}")
        return

    print(f"[INFO] Sorting calltree markdown: {calltree_path} ...")

    block_to_sig = {}
    with open(block_signature_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            if '=' in line:
                block_id, signature = line.split('=', 1)
                block_to_sig[int(block_id.strip())] = signature.strip()

    block_to_file = {}
    with open(block_line_mapping_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            if '=' in line:
                block_id, path_line = line.split('=', 1)

                full_path = path_line.rsplit(':', 1)[0].strip()
                normalized_path = full_path.replace('\\', '/')
                block_to_file[int(block_id.strip())] = normalized_path

    block_sequence = []
    with open(log_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#') or line.startswith('['):
                continue
            parts = [int(x.strip()) for x in line.split('->') if x.strip().isdigit()]
            block_sequence.extend(parts)

    abs_file_order = {}
    method_order = {}
    file_counter = 0
    method_counter = 0

    for block_id in block_sequence:
        file_path = block_to_file.get(block_id)
        if file_path and file_path not in abs_file_order:
            abs_file_order[file_path] = file_counter
            file_counter += 1

        method_sig = block_to_sig.get(block_id)
        if method_sig and method_sig not in method_order:
            method_order[method_sig] = method_counter
            method_counter += 1

    with open(calltree_path, 'r', encoding='utf-8') as f:
        content = f.read()

    thread_match = re.search(r'^(# Thread:.*)$', content, re.MULTILINE)
    if not thread_match:
        print("[WARNING] Could not find '# Thread:' in calltree markdown. Skipping sorting.")
        return

    header = content[:thread_match.start()]
    thread_body = content[thread_match.start():]

    file_sections = re.split(r'^(## File:\s*`([^`]+)`.*)$', thread_body, flags=re.MULTILINE)
    thread_header = file_sections[0].strip() + "\n\n"

    files_data = {}
    for i in range(1, len(file_sections), 3):
        file_title_line = file_sections[i]
        file_path = file_sections[i+1].strip()
        file_content = file_sections[i+2]

        method_sections = re.split(r'^(- \*\*Method:\*\* `([^`]+)`.*)$', file_content, flags=re.MULTILINE)
        methods_data = {}
        for j in range(1, len(method_sections), 3):
            m_title = method_sections[j]
            m_sig = method_sections[j+1].strip()
            m_body = method_sections[j+2]
            methods_data[m_sig] = m_title + m_body

        files_data[file_path] = {
            "file_header": file_title_line + "\n",
            "methods": methods_data
        }

    DEFAULT_WEIGHT = 999999
    file_order = {}
    for rel_path in files_data.keys():
        weight = DEFAULT_WEIGHT
        normalized_rel = rel_path.replace('\\', '/')
        for abs_path, order_val in abs_file_order.items():
            if abs_path.endswith(normalized_rel):
                weight = order_val
                break
        file_order[rel_path] = weight

    sorted_files = sorted(files_data.keys(), key=lambda f: file_order.get(f, DEFAULT_WEIGHT))

    output_md = []
    output_md.append(header.strip())
    output_md.append("\n\n" + thread_header.strip() + "\n\n")

    for file_path in sorted_files:
        file_info = files_data[file_path]
        output_md.append(file_info["file_header"])

        sorted_methods = sorted(file_info["methods"].keys(), key=lambda m: method_order.get(m, DEFAULT_WEIGHT))
        for method_sig in sorted_methods:
            output_md.append(file_info["methods"][method_sig].rstrip() + "\n")

        output_md.append("\n---\n\n")

    final_content = "".join(output_md)
    if final_content.endswith("\n---\n\n"):
        final_content = final_content[:-7] + "\n"

    with open(calltree_path, 'w', encoding='utf-8') as f:
        f.write(final_content)
    print(f"[INFO] Successfully sorted and updated calltree: {calltree_path}")

def process_logs(
    language="java",
    log_file=None,
    block_line_mapping_file=None,
    block_signature_file=None,
    events_file=None,
    target_folders_file=None,
    target_folders=None,
    pruned_folder="pruned\\",
    event_dictionary_file="event_dictionary.txt",
    block_pruner_jar=None,
    data_structuring_jar=None,
    base_reference_dir=None,
):
    """
    Core logic for processing instrumentation logs.

    Parameters correspond directly to the command-line arguments of the script.
    All path parameters can be relative to the current working directory or absolute.
    Raises exceptions on error instead of calling sys.exit.
    """

    if target_folders:
        target_folders_list = target_folders
        print(
            f"Using {len(target_folders_list)} target folder(s) from function argument.")
    else:
        target_folders_file = target_folders_file or ".\\target-folders.txt"
        if not os.path.isfile(target_folders_file):
            raise FileNotFoundError(
                f"Target folders file does not exist: {target_folders_file}")
        with open(target_folders_file, "r", encoding="utf-8") as f:
            lines = f.readlines()
        target_folders_list = [
            line.strip() for line in lines
            if line.strip() and not line.strip().startswith("#")
        ]
        if not target_folders_list:
            raise ValueError(
                f"No target folders found in file: {target_folders_file}")
        print(
            f"Loaded {len(target_folders_list)} target folder(s) from file: {target_folders_file}")

    for folder in target_folders_list:
        if not os.path.isdir(folder):
            raise NotADirectoryError(f"Target folder does not exist: {folder}")
    print(f"Target folders: {', '.join(target_folders_list)}")

    if not log_file:
        raise ValueError("log_file parameter is required")
    if not os.path.isfile(log_file):
        raise FileNotFoundError(f"Log file does not exist: {log_file}")
    if not block_line_mapping_file:
        raise ValueError("block_line_mapping_file parameter is required")
    if not os.path.isfile(block_line_mapping_file):
        raise FileNotFoundError(
            f"Comment mapping file does not exist: {block_line_mapping_file}")
    if not events_file:
        raise ValueError("events_file parameter is required")

    print(
        f"Starting log processing and data structuring for language: {language}...")
    print(f"  TargetFolders:      {'; '.join(target_folders_list)}")
    print(f"  LogFile:            {log_file}")
    print(f"  CommentMappingFile: {block_line_mapping_file}")
    if block_signature_file:
        print(f"  BlockSignatureFile: {block_signature_file}")
    print(f"  PrunedFolder:       {pruned_folder}")
    print(f"  EventsFile:         {events_file}")
    print(f"  EventDictionaryFile:{event_dictionary_file}")
    if base_reference_dir:
        print(f"  BaseReferenceDir:   {base_reference_dir}")

    if language == "java":
        _process_java_logs(
            target_folders_list, log_file, block_line_mapping_file, events_file,
            pruned_folder, event_dictionary_file, block_pruner_jar, data_structuring_jar,
            base_reference_dir
        )
    elif language == "python":
        _process_python_logs(
            target_folders_list, log_file, block_line_mapping_file, events_file,
            pruned_folder, event_dictionary_file, base_reference_dir
        )
    elif language == "php":
        _process_php_logs(
            target_folders_list, log_file, block_line_mapping_file, events_file,
            pruned_folder, event_dictionary_file, base_reference_dir
        )
    elif language in ["javascript", "js"]:
        _process_javascript_logs(
            target_folders_list, log_file, block_line_mapping_file, events_file,
            pruned_folder, event_dictionary_file, base_reference_dir
        )
    else:
        raise ValueError(f"Unsupported language: {language}")

    if block_signature_file and os.path.isfile(block_signature_file):

        possible_paths = [
            os.path.join(os.path.dirname(events_file) or ".", "final-output-calltree.md"),
            os.path.join(pruned_folder, "final-output-calltree.md"),
            "final-output-calltree.md"
        ]
        found_calltree = None
        for path in possible_paths:
            if os.path.isfile(path):
                found_calltree = path
                break

        if found_calltree:
            try:
                _sort_calltree_markdown(found_calltree, log_file, block_line_mapping_file, block_signature_file)
                
                print("[INFO] Calltree sorted. Starting signature order analysis and flow report generation...")
                try:
                    try:
                        from .parser_signature_order import analyze_thread_flow
                        from .present_execution_flow_with_code import generate_flow_report
                    except (ImportError, ValueError):
                        current_dir = os.path.dirname(os.path.abspath(__file__))
                        if current_dir not in sys.path:
                            sys.path.append(current_dir)
                        from parser_signature_order import analyze_thread_flow
                        from present_execution_flow_with_code import generate_flow_report

                    print("[INFO] Running analyze_thread_flow...")
                    analyze_thread_flow(
                        log_file=log_file,
                        block_signature_file=block_signature_file,
                        block_line_mapping_file=block_line_mapping_file
                    )


                    sig_file_cwd = os.path.join(os.getcwd(), "signature_order.txt")
                    calltree_file_cwd = os.path.join(os.getcwd(), "final-output-calltree.md")
                    output_file_cwd = os.path.join(os.getcwd(), "execution_flow_with_code.md")

                    print("[INFO] Running generate_flow_report...")
                    generate_flow_report(
                        signature_file=sig_file_cwd,
                        calltree_file=calltree_file_cwd,
                        output_file=output_file_cwd
                    )

                except Exception as flow_err:
                    print(f"[WARNING] Failed to generate execution flow report: {flow_err}", file=sys.stderr)
                # ------------------------------------------------------------------

            except Exception as e:
                print(f"[WARNING] Failed to sort calltree markdown: {e}", file=sys.stderr)
        else:
            print("[INFO] block_signature_file was provided, but 'final-output-calltree.md' was not found in expected paths.")

    print("Log processing, data structuring, and source code restoration completed successfully!")

def _process_java_logs(target_folders_list, log_file, block_line_mapping_file, events_file, pruned_folder, event_dictionary_file, block_pruner_jar, data_structuring_jar, base_reference_dir=None):
    """Specific logic for processing Java logs using JAR files."""

    if not block_pruner_jar:
        block_pruner_jar = str(PROJECT_ROOT / "multilingual" / "java" /
                               "block-pruner" / "target" / "block-pruner-1.0-SNAPSHOT.jar")
    if not data_structuring_jar:
        data_structuring_jar = str(PROJECT_ROOT / "multilingual" / "java" /
                                   "data-structuring" / "target" / "data-structuring-1.0-SNAPSHOT.jar")

    print("Checking Java environment variables...")
    java_home = os.environ.get("JAVA_HOME")
    if not java_home:
        raise EnvironmentError(
            "JAVA_HOME environment variable not configured. "
            "Please set JAVA_HOME to point to your JDK installation directory."
        )
    print(f"Using JAVA_HOME: {java_home}")

    env = os.environ.copy()
    env["PATH"] = os.path.join(java_home, "bin") + \
        os.pathsep + env.get("PATH", "")

    print("Executing Java Block Pruner...")
    source_dirs_arg = ";".join(target_folders_list)
    block_pruner_cmd = [
        "java", "-jar", block_pruner_jar,
        source_dirs_arg,
        block_line_mapping_file,
        log_file,
        pruned_folder
    ]
    if base_reference_dir:
        block_pruner_cmd.append(base_reference_dir)

    try:
        subprocess.run(block_pruner_cmd, env=env, check=True)
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Error executing Block Pruner: {e}")

    print("Executing Java Data Structuring...")
    data_struct_cmd = [
        "java", "-jar", data_structuring_jar,
        pruned_folder,
        block_line_mapping_file,
        log_file,
        events_file,
        event_dictionary_file
    ]
    try:
        subprocess.run(data_struct_cmd, env=env, check=True)
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Error executing Data Structuring: {e}")

def _process_python_logs(target_folders_list, log_file, block_line_mapping_file, events_file, pruned_folder, event_dictionary_file, base_reference_dir=None):
    """Specific logic for processing Python logs."""
    print("Executing Python log processing tools...")

    print("[INFO] Python log processing is currently a stub and needs implementation.")

def _process_php_logs(target_folders_list, log_file, block_line_mapping_file, events_file, pruned_folder, event_dictionary_file, base_reference_dir=None):
    """Specific logic for processing PHP logs."""
    print("Executing PHP log processing tools...")

    env = os.environ.copy()

    print("Executing PHP Block Pruner...")
    php_pruner_script_path = str(
        PROJECT_ROOT / "multilingual" / "php" / "block-pruner" / "BlockPruner.php")
    source_dirs_arg = ";".join(target_folders_list)

    php_pruner_cmd = [
        "php",
        php_pruner_script_path,
        source_dirs_arg,
        block_line_mapping_file,
        log_file,
        pruned_folder
    ]
    if base_reference_dir:
        php_pruner_cmd.append(base_reference_dir)

    print(f"Running command: {' '.join(php_pruner_cmd)}")
    try:
        subprocess.run(php_pruner_cmd, env=env, check=True)
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Error executing PHP Block Pruner: {e}")

    print("Executing PHP Data Structuring...")
    php_structuring_script_path = str(
        PROJECT_ROOT / "multilingual" / "php" / "data-structuring" / "bin" / "data-structuring.php")

    php_structuring_cmd = [
        "php",
        php_structuring_script_path,
        pruned_folder,
        block_line_mapping_file,
        log_file
    ]

    print(f"Running command: {' '.join(php_structuring_cmd)}")
    try:
        subprocess.run(php_structuring_cmd, env=env, check=True)
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Error executing PHP Data Structuring: {e}")

def _process_javascript_logs(target_folders_list, log_file, block_line_mapping_file, events_file, pruned_folder, event_dictionary_file, base_reference_dir=None):
    """Specific logic for processing JavaScript logs."""
    print("Executing JavaScript log processing tools...")

    env = os.environ.copy()

    print("Executing JavaScript Block Pruner...")
    js_pruner_script_path = str(
        PROJECT_ROOT / "multilingual" / "javascript" / "block-pruner" / "BlockPruner.js")
    source_dirs_arg = ";".join(target_folders_list)

    js_pruner_cmd = [
        "node",
        js_pruner_script_path,
        source_dirs_arg,
        block_line_mapping_file,
        log_file,
        pruned_folder
    ]
    if base_reference_dir:
        js_pruner_cmd.append(base_reference_dir)

    print(f"Running command: {' '.join(js_pruner_cmd)}")
    try:
        subprocess.run(js_pruner_cmd, env=env, check=True)
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Error executing JavaScript Block Pruner: {e}")

    print("Executing JavaScript Data Structuring...")
    js_structuring_script_path = str(
        PROJECT_ROOT / "multilingual" / "javascript" / "data-structuring" / "DataStructuring.js")

    js_structuring_cmd = [
        "node",
        js_structuring_script_path,
        pruned_folder
    ]

    print(f"Running command: {' '.join(js_structuring_cmd)}")
    try:
        subprocess.run(js_structuring_cmd, env=env, check=True)
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Error executing JavaScript Data Structuring: {e}")

def main():
    parser = argparse.ArgumentParser(
        description="Processes the log files generated by tests and restores the source code."
    )
    parser.add_argument(
        "--language",
        default="java",
        help="Target programming language (default: java)"
    )
    parser.add_argument(
        "--target-folders-file",
        default=".\\target-folders.txt",
        help="File containing target folder paths (one per line). Lines starting with '#' and empty lines are ignored. Default: .\\target-folders.txt"
    )
    parser.add_argument(
        "--target-folders",
        nargs="+",
        help="One or more target folder paths. If specified, takes precedence over --target-folders-file."
    )
    parser.add_argument(
        "--log-file",
        required=True,
        help="Path to the deduplicated instrumentation log file"
    )
    parser.add_argument(
        "--block-line-mapping-file",
        required=True,
        help="Path to the comment mapping file"
    )
    parser.add_argument(
        "--block-signature-file",
        default=None,
        help="Path to the block-signature mapping file. If provided, final-output-calltree.md will be automatically sorted."
    )
    parser.add_argument(
        "--pruned-folder",
        default="pruned\\",
        help="Path to the pruned output folder (default: pruned\\)"
    )
    parser.add_argument(
        "--events-file",
        required=True,
        help="Path to the structured events output file"
    )
    parser.add_argument(
        "--event-dictionary-file",
        default="event_dictionary.txt",
        help="Path to the event dictionary output file (default: event_dictionary.txt)"
    )
    parser.add_argument(
        "--block-pruner-jar",
        default=None,
        help="Path to the Block Pruner jar (defaults to Javatarget path)"
    )
    parser.add_argument(
        "--data-structuring-jar",
        default=None,
        help="Path to the Data Structuring jar (defaults to Javatarget path)"
    )
    parser.add_argument(
        "--base-reference-dir",
        default=None,
        help="Base directory to preserve relative directory structures"
    )

    args = parser.parse_args()

    try:
        process_logs(
            language=args.language,
            target_folders_file=args.target_folders_file,
            target_folders=args.target_folders,
            log_file=args.log_file,
            block_line_mapping_file=args.block_line_mapping_file,
            block_signature_file=args.block_signature_file,
            pruned_folder=args.pruned_folder,
            events_file=args.events_file,
            event_dictionary_file=args.event_dictionary_file,
            block_pruner_jar=args.block_pruner_jar,
            data_structuring_jar=args.data_structuring_jar,
            base_reference_dir=args.base_reference_dir,
        )
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()