#!/usr/bin/env python3
"""
Processes the log files generated by tests (pruning, data structuring) and restores the source code.

Accepts absolute (or relative) paths for all input/output files.
Supports multiple target folders via a file or direct parameter, consistent with run-instrumentation-demo.ps1.
The input log file is expected to be already deduplicated (e.g., produced by the JUnit listener).

This module can be used both as a CLI script and as an imported function.
"""

import argparse
import os
import sys
import subprocess
from pathlib import Path


def process_logs(
    log_file=None,
    comment_mapping_file=None,
    events_file=None,
    target_folders_file=None,
    target_folders=None,
    pruned_folder="pruned\\",
    event_dictionary_file="event_dictionary.txt",
    block_pruner_jar=".\\core\\block-pruner\\target\\block-pruner-1.0-SNAPSHOT.jar",
    data_structuring_jar=".\\core\\data-structuring\\target\\data-structuring-1.0-SNAPSHOT.jar",
):
    """
    Core logic for processing instrumentation logs.

    Parameters correspond directly to the command-line arguments of the script.
    All path parameters can be relative to the current working directory or absolute.
    Raises exceptions on error instead of calling sys.exit.
    """
    # --- Resolve target folders (same pattern as PowerShell) ---
    if target_folders:
        target_folders_list = target_folders
        print(f"Using {len(target_folders_list)} target folder(s) from function argument.")
    else:
        target_folders_file = target_folders_file or ".\\target-folders.txt"
        if not os.path.isfile(target_folders_file):
            raise FileNotFoundError(f"Target folders file does not exist: {target_folders_file}")
        with open(target_folders_file, "r", encoding="utf-8") as f:
            lines = f.readlines()
        target_folders_list = [
            line.strip() for line in lines
            if line.strip() and not line.strip().startswith("#")
        ]
        if not target_folders_list:
            raise ValueError(f"No target folders found in file: {target_folders_file}")
        print(f"Loaded {len(target_folders_list)} target folder(s) from file: {target_folders_file}")

    # Validate each folder exists
    for folder in target_folders_list:
        if not os.path.isdir(folder):
            raise NotADirectoryError(f"Target folder does not exist: {folder}")
    print(f"Target folders: {', '.join(target_folders_list)}")

    # Verify critical input files
    if not log_file:
        raise ValueError("log_file parameter is required")
    if not os.path.isfile(log_file):
        raise FileNotFoundError(f"Log file does not exist: {log_file}")
    if not comment_mapping_file:
        raise ValueError("comment_mapping_file parameter is required")
    if not os.path.isfile(comment_mapping_file):
        raise FileNotFoundError(f"Comment mapping file does not exist: {comment_mapping_file}")
    if not events_file:
        raise ValueError("events_file parameter is required")

    # Check Java environment variables
    print("Checking Java environment variables...")
    java_home = os.environ.get("JAVA_HOME")
    if not java_home:
        raise EnvironmentError(
            "JAVA_HOME environment variable not configured. "
            "Please set JAVA_HOME to point to your JDK installation directory."
        )
    print(f"Using JAVA_HOME: {java_home}")
    os.environ["PATH"] = os.path.join(java_home, "bin") + os.pathsep + os.environ.get("PATH", "")

    # Print configuration summary
    print("Starting log processing and data structuring...")
    print(f"  TargetFolders:      {'; '.join(target_folders_list)}")
    print(f"  LogFile:            {log_file}")
    print(f"  CommentMappingFile: {comment_mapping_file}")
    print(f"  PrunedFolder:       {pruned_folder}")
    print(f"  EventsFile:         {events_file}")
    print(f"  EventDictionaryFile:{event_dictionary_file}")

    # 1. Execute Block Pruner
    print("Executing Block Pruner...")
    source_dirs_arg = ";".join(target_folders_list)
    block_pruner_cmd = [
        "java", "-jar", block_pruner_jar,
        source_dirs_arg,
        comment_mapping_file,
        log_file,
        pruned_folder
    ]
    try:
        subprocess.run(block_pruner_cmd, check=True)
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Error executing Block Pruner: {e}")

    # 2. Execute Data Structuring
    print("Executing Data Structuring...")
    data_struct_cmd = [
        "java", "-jar", data_structuring_jar,
        pruned_folder,
        comment_mapping_file,
        log_file,
        events_file,
        event_dictionary_file
    ]
    try:
        subprocess.run(data_struct_cmd, check=True)
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Error executing Data Structuring: {e}")

    print("Log processing, data structuring, and source code restoration completed successfully!")


def main():
    parser = argparse.ArgumentParser(
        description="Processes the log files generated by tests and restores the source code."
    )
    parser.add_argument(
        "--target-folders-file",
        default=".\\target-folders.txt",
        help="File containing target folder paths (one per line). Lines starting with '#' and empty lines are ignored. Default: .\\target-folders.txt"
    )
    parser.add_argument(
        "--target-folders",
        nargs="+",
        help="One or more target folder paths. If specified, takes precedence over --target-folders-file."
    )
    parser.add_argument(
        "--log-file",
        required=True,
        help="Path to the deduplicated instrumentation log file"
    )
    parser.add_argument(
        "--comment-mapping-file",
        required=True,
        help="Path to the comment mapping file"
    )
    parser.add_argument(
        "--pruned-folder",
        default="pruned\\",
        help="Path to the pruned output folder (default: pruned\\)"
    )
    parser.add_argument(
        "--events-file",
        required=True,
        help="Path to the structured events output file"
    )
    parser.add_argument(
        "--event-dictionary-file",
        default="event_dictionary.txt",
        help="Path to the event dictionary output file (default: event_dictionary.txt)"
    )
    parser.add_argument(
        "--block-pruner-jar",
        default=".\\core\\block-pruner\\target\\block-pruner-1.0-SNAPSHOT.jar",
        help="Path to the Block Pruner jar"
    )
    parser.add_argument(
        "--data-structuring-jar",
        default=".\\core\\data-structuring\\target\\data-structuring-1.0-SNAPSHOT.jar",
        help="Path to the Data Structuring jar"
    )

    args = parser.parse_args()

    try:
        process_logs(
            target_folders_file=args.target_folders_file,
            target_folders=args.target_folders,
            log_file=args.log_file,
            comment_mapping_file=args.comment_mapping_file,
            pruned_folder=args.pruned_folder,
            events_file=args.events_file,
            event_dictionary_file=args.event_dictionary_file,
            block_pruner_jar=args.block_pruner_jar,
            data_structuring_jar=args.data_structuring_jar,
        )
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()