#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import sys
import re
import json

# ==========================================
# 1. Define Prompt Template
# ==========================================

APPLY_FIX_PROMPT_TEMPLATE = """# Code Fix Implementation Task

You are an expert software engineer. Your task is to apply a specific bug fix to the provided source files based on the diagnostic report.

---

## Bug Fix Plan

The following is the diagnostic report and fix plan generated by the bug localization system. It describes the root cause and how the code should be modified.

### [Diagnostic Report & Fix Plan]
=========================================
{fix_plan}
=========================================

---

## Original Source Files

Below are the complete original contents of the files that need to be modified. 

{original_files_content}

---

## Task Requirements

1. **Understand the Fix**: Read the Bug Fix Plan carefully to understand the required logical changes.
2. **Apply the Fix**: Apply the exact modifications described in the fix plan to the original source files provided above.
3. **Complete Code Only**: You MUST output the **entire, complete modified code** for each file. Do NOT use `...` to omit any part of the code. The output must be ready to be directly written to the file system.
4. **Preserve Formatting**: Maintain the original indentation, imports, and code structure unless they are part of the fix. Add comments like `// [Bug Fix]` at the changed parts if requested by the fix plan.

---

## Output Format Requirements

To allow automated tools to parse your response and overwrite the local files, you **MUST** strictly follow the output format below for EACH modified file. 

- Enclose the complete file content between `<!-- FILE_CONTENT_START: [filepath] -->` and `<!-- FILE_CONTENT_END -->`.
- Use the exact `[filepath]` provided in the Original Source Files section.
- Do NOT wrap the code inside markdown code blocks (```java ... ```) INSIDE the markers. The content between the markers should be the raw file content.
- Do not add any extra text, explanations, or markdown formatting inside the markers.

### Example Output Format:

<!-- FILE_CONTENT_START: path/to/first/file.ext -->
public class Example {{
    // complete modified code here
}}
<!-- FILE_CONTENT_END -->

<!-- FILE_CONTENT_START: path/to/second/file.ext -->
import java.util.*;

public class SecondExample {{
    // complete modified code here
}}
<!-- FILE_CONTENT_END -->

### Your Implementation:
"""

# ==========================================
# 2. Core Logic
# ==========================================

def extract_files_to_modify(output_md_content):
    """Extract file paths from the output.md content."""
    pattern = r'<!-- FILES_TO_MODIFY_START -->(.*?)<!-- FILES_TO_MODIFY_END -->'
    match = re.search(pattern, output_md_content, re.DOTALL)
    
    if not match:
        return []
    
    files_text = match.group(1).strip()
    if not files_text or files_text == "NONE":
        return []
    
    # Split by lines and clean up
    files = [line.strip() for line in files_text.split('\n') if line.strip()]
    return files

def resolve_file_path(relative_path, base_dirs):
    """
    Search for the relative path inside the given base directories.
    It will also do a recursive search to handle cases like 'src/main/java/...' 
    when the relative path is just the package name 'com/example/...'.
    """
    # Normalize the relative path for the current OS (e.g., replace / with \)
    norm_rel_path = os.path.normpath(relative_path)
    
    for base_dir in base_dirs:
        if not os.path.exists(base_dir):
            continue
            
        # 1. First, try direct join (fastest)
        direct_path = os.path.normpath(os.path.join(base_dir, norm_rel_path))
        if os.path.exists(direct_path) and os.path.isfile(direct_path):
            return direct_path
            
        # 2. If not found directly, do a recursive search in the base_dir
        for root, dirs, files in os.walk(base_dir):
            for file in files:
                full_path = os.path.join(root, file)
                # If the absolute path ends with the normalized relative path, it's a match!
                if full_path.endswith(norm_rel_path):
                    return full_path
                    
    return None

def generate_prompt(proj_path=None, report_path=None):
    """
    Exposed interface to generate the fix prompt.
    Automatically reads the diagnostic report and target folders from config.json.
    """
    print("="*50)
    print("  AI Bug Fix Prompt Auto Generator")
    print("="*50)
    
    # 1. Get output.md path automatically
    if not report_path:
        report_path = "output.md"
        
    if not os.path.exists(report_path):
        print(f"[!] Error: Diagnostic report '{report_path}' not found.")
        return False
        
    # 2. Get base directories automatically from project config
    base_dirs = ["."]
    if proj_path:
        config_path = os.path.join(proj_path, 'config.json')
        if os.path.exists(config_path):
            try:
                with open(config_path, 'r', encoding='utf-8') as f:
                    config_data = json.load(f)
                    base_dirs = config_data.get('original-target-folders', [])
                    if not base_dirs:
                        print("[Warning] 'original-target-folders' is empty in config.json. Using current directory as fallback.")
                        base_dirs = ["."]
            except Exception as e:
                print(f"[!] Failed to read config.json: {e}")
        else:
            print(f"[Warning] Project config not found at: {config_path}. Using current directory as fallback.")
    else:
        print("[Warning] No project path provided. Using current directory as fallback.")

    print(f"[+] Loaded {len(base_dirs)} base directory path(s) for searching.")

    # Read fix plan
    try:
        with open(report_path, 'r', encoding='utf-8') as f:
            fix_plan_content = f.read()
    except Exception as e:
        print(f"[!] Failed to read {report_path}: {e}")
        return False
        
    # Extract files to modify
    files_to_modify = extract_files_to_modify(fix_plan_content)
    
    if not files_to_modify:
        print("[+] No files to modify found in the report (or marked as NONE). Exiting.")
        return True
        
    print(f"\n[Search] Found {len(files_to_modify)} file(s) to modify. Searching in base directories...")
    
    # Read original files by resolving their absolute paths
    original_files_content = ""
    for rel_path in files_to_modify:
        abs_path = resolve_file_path(rel_path, base_dirs)
        
        if not abs_path:
            print(f"   [-] Could not find: {rel_path}")
            original_files_content += f"### File: `{rel_path}`\n[File not found locally in any base directory. Please generate complete content based on the fix plan.]\n\n"
            continue
            
        print(f"   [+] Found: {abs_path}")
        try:
            with open(abs_path, 'r', encoding='utf-8') as f:
                content = f.read()
            # We keep the relative path in the prompt so the AI outputs the relative path,
            # which is easier for the downstream tool to map back.
            original_files_content += f"### File: `{rel_path}`\n```\n{content}\n```\n\n"
        except Exception as e:
            print(f"   [!] Failed to read local file {abs_path}: {e}")
            return False
            
    # Assemble final prompt
    final_prompt = APPLY_FIX_PROMPT_TEMPLATE.format(
        fix_plan=fix_plan_content,
        original_files_content=original_files_content
    )
    
    # Write to file
    prompt_filename = "AI_Apply_Fix_Prompt.md"
    try:
        with open(prompt_filename, 'w', encoding='utf-8') as f:
            f.write(final_prompt)
        print("\n" + "="*50)
        print(f"[Success] The fix prompt has been generated and saved as: {prompt_filename}")
        print("[Info] You can now send this file to the LLM to get the fully modified code!")
        print("="*50)
        return True
    except Exception as e:
        print(f"\n[!] Failed to save prompt file: {e}")
        return False

if __name__ == "__main__":
    try:
        generate_prompt()
    except KeyboardInterrupt:
        print("\n\n[!] Operation cancelled by user.")
        sys.exit(0)