#!/usr/bin/env python3
"""
Processes the log files generated by tests (pruning, data structuring) and restores the source code.
Now leverages Codebase-Memory (CBM) for high-performance, multi-language data structuring.

Accepts absolute (or relative) paths for all input/output files.
Supports multiple target folders via a file or direct parameter.
"""

from collections import defaultdict
import argparse
import os, shutil, glob
import sys
import subprocess
from functools import lru_cache
import json
import re
from pathlib import Path

# Dynamically resolve the project root (one level up from 'engineering' folder)
PROJECT_ROOT = Path(__file__).resolve().parent.parent

# --- Tree-sitter Configuration for Multi-language Support ---
try:
    import tree_sitter_languages
except ImportError:
    # We will raise a runtime error if CBM data structuring is run and tree-sitter is missing.
    tree_sitter_languages = None


# ============================================================================
# Robust function-body extraction via Tree-sitter, keyed by qualified_name.
# ============================================================================
#
# Per-language config:
#   (ts_lang, function_node_types, class_node_types, namespace_node_types,
#    class_separator, namespace_separator)
#
LANG_CONFIG = {
    ".php":  ("php",
              {"function_definition", "method_declaration"},
              {"class_declaration", "interface_declaration",
               "trait_declaration", "enum_declaration"},
              {"namespace_definition"},
              "::", "\\"),
    ".py":   ("python",
              {"function_definition"},
              {"class_definition"},
              set(),
              ".", "."),
    ".java": ("java",
              {"method_declaration", "constructor_declaration"},
              {"class_declaration", "interface_declaration",
               "enum_declaration", "record_declaration"},
              {"package_declaration"},
              ".", "."),
    ".go":   ("go",
              {"function_declaration", "method_declaration"},
              set(),
              {"package_clause"},
              ".", "."),
    ".js":   ("javascript",
              {"function_declaration", "method_definition",
               "function_expression", "arrow_function"},
              {"class_declaration"},
              set(),
              ".", "."),
    ".ts":   ("typescript",
              {"function_declaration", "method_definition",
               "function_signature"},
              {"class_declaration", "interface_declaration"},
              {"module"},
              ".", "."),
}

NAME_NODE_TYPES = ("name", "identifier", "field_identifier",
                   "type_identifier", "namespace_name", "scoped_identifier")
BODY_NODE_TYPES = ("block", "compound_statement", "function_body",
                   "statement_block", "class_body")


def _normalize_qname(qname):
    """
    Normalize a qualified name so that CBM's representation and
    tree-sitter's reconstructed name can be compared reliably.
    Collapses '::', '\\', '/' and '.' to a single separator '/'.
    Strips leading separators.
    """
    if not qname:
        return ""
    s = qname.replace("::", "/").replace("\\", "/").replace(".", "/")
    s = s.strip("/")
    # Collapse repeated slashes
    while "//" in s:
        s = s.replace("//", "/")
    return s


@lru_cache(maxsize=1024)
def build_function_index(file_path):
    """
    Parse `file_path` once and build:
        { normalized_qualified_name : entry  OR  [entry, entry, ...] }
    Each entry contains: name, qualified_name, signature, body,
    start_line, end_line.

    Cached so repeated lookups against the same file cost nothing.
    """
    if not tree_sitter_languages:
        return {}
    ext = os.path.splitext(file_path)[1].lower()
    if ext not in LANG_CONFIG:
        return {}

    lang_name, func_types, class_types, ns_types, csep, nsep = LANG_CONFIG[ext]

    try:
        parser = tree_sitter_languages.get_parser(lang_name)
        with open(file_path, "rb") as f:
            src = f.read()
        tree = parser.parse(src)
    except Exception as e:
        print(f"[WARN] tree-sitter failed to parse {file_path}: {e}")
        return {}

    def text(node):
        return src[node.start_byte:node.end_byte].decode("utf-8", errors="ignore")

    def get_name(node):
        # Prefer explicit field 'name' (more accurate for many grammars)
        n = node.child_by_field_name("name")
        if n is not None:
            return text(n)
        for c in node.children:
            if c.type in NAME_NODE_TYPES:
                return text(c)
        return None

    index = {}

    def add_entry(qname, entry):
        key = _normalize_qname(qname)
        if not key:
            return
        if key in index:
            existing = index[key]
            if isinstance(existing, list):
                existing.append(entry)
            else:
                index[key] = [existing, entry]
        else:
            index[key] = entry

    def walk(node, ns_path, class_path):
        t = node.type

        # Namespace / package
        if t in ns_types:
            nm = get_name(node) or ""
            new_ns = (ns_path + nsep + nm) if (ns_path and nm) else (nm or ns_path)
            for c in node.children:
                walk(c, new_ns, class_path)
            return

        # Class / interface / trait / enum
        if t in class_types:
            nm = get_name(node) or "<anon>"
            new_cls = (class_path + csep + nm) if class_path else nm
            for c in node.children:
                walk(c, ns_path, new_cls)
            return

        # Function / method
        if t in func_types:
            nm = get_name(node) or "<anon>"
            prefix = ""
            if ns_path:
                prefix += ns_path + nsep
            if class_path:
                prefix += class_path + csep
            qname = prefix + nm

            body_node = next(
                (c for c in node.children if c.type in BODY_NODE_TYPES), None)
            full = text(node)
            if body_node:
                sig = src[node.start_byte:body_node.start_byte].decode(
                    "utf-8", errors="ignore").strip()
            else:
                sig = full.splitlines()[0] if full else nm

            entry = {
                "name": nm,
                "qualified_name": qname,
                "signature": sig,
                "body": full,
                "start_line": node.start_point[0] + 1,
                "end_line":   node.end_point[0] + 1,
            }

            # Index under its full qname...
            add_entry(qname, entry)
            # ...and also under simple name (for fallback lookups when
            # CBM's qname doesn't match our reconstructed one exactly).
            add_entry(nm, entry)

            # Don't descend into function bodies (nested functions are rare
            # in the languages we care about; opt-in via a flag if needed).
            return

        for c in node.children:
            walk(c, ns_path, class_path)

    walk(tree.root_node, "", "")
    return index


def lookup_function(file_path, qualified_name=None,
                    fallback_name=None, hint_line=None):
    """
    Locate a function entry in `file_path`.

    Strategy (in order):
      1. Exact match on normalized qualified_name.
      2. Suffix match: any indexed key that ends with the requested
         normalized qname (handles CBM having extra namespace prefix
         that tree-sitter couldn't reconstruct, or vice versa).
      3. Simple-name match using fallback_name. If multiple candidates,
         pick the closest by hint_line; if no hint_line and >1 candidate,
         refuse (return None).

    Returns the entry dict or None. Never returns a wrong-name match.
    """
    idx = build_function_index(file_path)
    if not idx:
        return None

    def pick(entry_or_list):
        if isinstance(entry_or_list, list):
            if hint_line is not None:
                return min(entry_or_list,
                           key=lambda it: abs(it["start_line"] - hint_line))
            return entry_or_list[0]
        return entry_or_list

    # 1) Exact normalized qname
    if qualified_name:
        norm = _normalize_qname(qualified_name)
        if norm in idx:
            return pick(idx[norm])

        # 2) Suffix matching in either direction
        suffix_hits = []
        for k, v in idx.items():
            if k.endswith("/" + norm) or norm.endswith("/" + k):
                items = v if isinstance(v, list) else [v]
                suffix_hits.extend(items)
        if len(suffix_hits) == 1:
            return suffix_hits[0]
        if len(suffix_hits) > 1:
            # Prefer name-matching candidates first
            if fallback_name:
                name_hits = [it for it in suffix_hits
                             if it["name"] == fallback_name]
                if name_hits:
                    suffix_hits = name_hits
            if hint_line is not None:
                return min(suffix_hits,
                           key=lambda it: abs(it["start_line"] - hint_line))
            return suffix_hits[0]

    # 3) Plain-name fallback
    if fallback_name:
        norm_simple = _normalize_qname(fallback_name)
        if norm_simple in idx:
            entry = idx[norm_simple]
            items = entry if isinstance(entry, list) else [entry]
            # Filter to entries whose own name == fallback_name
            items = [it for it in items if it["name"] == fallback_name]
            if len(items) == 1:
                return items[0]
            if len(items) > 1:
                if hint_line is not None:
                    return min(items,
                               key=lambda it: abs(it["start_line"] - hint_line))
                # Multiple candidates and no way to disambiguate -> refuse
                return None

    return None


# ============================================================================
# Main pipeline
# ============================================================================
def process_logs(
    language="java",
    log_file=None,
    comment_mapping_file=None,
    events_file=None,
    target_folders_file=None,
    target_folders=None,
    pruned_folder="pruned\\",
    event_dictionary_file="event_dictionary.txt",
    block_pruner_jar=None,
    base_reference_dir=None,
):
    """
    Core logic for processing instrumentation logs.
    """
    # --- Resolve target folders ---
    if target_folders:
        target_folders_list = target_folders
        print(
            f"Using {len(target_folders_list)} target folder(s) from function argument.")
    else:
        target_folders_file = target_folders_file or ".\\target-folders.txt"
        if not os.path.isfile(target_folders_file):
            raise FileNotFoundError(
                f"Target folders file does not exist: {target_folders_file}")
        with open(target_folders_file, "r", encoding="utf-8") as f:
            lines = f.readlines()
        target_folders_list = [
            line.strip() for line in lines
            if line.strip() and not line.strip().startswith("#")
        ]
        if not target_folders_list:
            raise ValueError(
                f"No target folders found in file: {target_folders_file}")
        print(
            f"Loaded {len(target_folders_list)} target folder(s) from file: {target_folders_file}")

    # Validate each folder exists
    for folder in target_folders_list:
        if not os.path.isdir(folder):
            raise NotADirectoryError(f"Target folder does not exist: {folder}")
    print(f"Target folders: {', '.join(target_folders_list)}")

    # Verify critical input files
    if not log_file:
        raise ValueError("log_file parameter is required")
    if not os.path.isfile(log_file):
        raise FileNotFoundError(f"Log file does not exist: {log_file}")
    if not comment_mapping_file:
        raise ValueError("comment_mapping_file parameter is required")
    if not os.path.isfile(comment_mapping_file):
        raise FileNotFoundError(
            f"Comment mapping file does not exist: {comment_mapping_file}")
    if not events_file:
        raise ValueError("events_file parameter is required")

    # Print configuration summary
    print(
        f"Starting log processing and data structuring for language: {language}...")
    print(f"  TargetFolders:      {'; '.join(target_folders_list)}")
    print(f"  LogFile:            {log_file}")
    print(f"  CommentMappingFile: {comment_mapping_file}")
    print(f"  PrunedFolder:       {pruned_folder}")
    print(f"  EventsFile:         {events_file}")
    print(f"  EventDictionaryFile:{event_dictionary_file}")
    if base_reference_dir:
        print(f"  BaseReferenceDir:   {base_reference_dir}")

    # Step 1: Execute Block Pruner (Language-specific)
    if language == "java":
        _run_java_pruner(target_folders_list, log_file, comment_mapping_file,
                         pruned_folder, block_pruner_jar, base_reference_dir)
    elif language == "python":
        _run_python_pruner(target_folders_list, log_file,
                           comment_mapping_file, pruned_folder, base_reference_dir)
    elif language == "php":
        _run_php_pruner(target_folders_list, log_file,
                        comment_mapping_file, pruned_folder, base_reference_dir)
    elif language in ["javascript", "js"]:
        _run_javascript_pruner(target_folders_list, log_file,
                               comment_mapping_file, pruned_folder, base_reference_dir)
    else:
        raise ValueError(f"Unsupported language: {language}")

    # Step 2: Unified Data Structuring using Codebase-Memory & Tree-sitter
    _run_cbm_data_structuring(pruned_folder)

    print("Log processing, data structuring, and source code restoration completed successfully!")


def _run_java_pruner(target_folders_list, log_file, comment_mapping_file, pruned_folder, block_pruner_jar, base_reference_dir=None):
    """Specific logic for executing Java Block Pruner."""
    if not block_pruner_jar:
        block_pruner_jar = str(PROJECT_ROOT / "multilingual" / "java" /
                               "block-pruner" / "target" / "block-pruner-1.0-SNAPSHOT.jar")

    print("Checking Java environment variables...")
    java_home = os.environ.get("JAVA_HOME")
    if not java_home:
        raise EnvironmentError(
            "JAVA_HOME environment variable not configured. Please set JAVA_HOME."
        )
    env = os.environ.copy()
    env["PATH"] = os.path.join(java_home, "bin") + \
        os.pathsep + env.get("PATH", "")

    print("Executing Java Block Pruner...")
    source_dirs_arg = ";".join(target_folders_list)
    block_pruner_cmd = [
        "java", "-jar", block_pruner_jar,
        source_dirs_arg,
        comment_mapping_file,
        log_file,
        pruned_folder
    ]
    if base_reference_dir:
        block_pruner_cmd.append(base_reference_dir)

    try:
        subprocess.run(block_pruner_cmd, env=env, check=True)
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Error executing Block Pruner: {e}")


def _run_python_pruner(target_folders_list, log_file, comment_mapping_file, pruned_folder, base_reference_dir=None):
    """Specific logic for executing Python Block Pruner."""
    print("Executing Python Block Pruner...")
    # Stub for Python pruner (if implemented in future)
    print("[INFO] Python block pruner is currently a stub.")


def _run_php_pruner(target_folders_list, log_file, comment_mapping_file, pruned_folder, base_reference_dir=None):
    """Specific logic for executing PHP Block Pruner."""
    print("Executing PHP Block Pruner...")
    php_pruner_script_path = str(
        PROJECT_ROOT / "multilingual" / "php" / "block-pruner" / "BlockPruner.php")
    source_dirs_arg = ";".join(target_folders_list)

    php_pruner_cmd = [
        "php",
        php_pruner_script_path,
        source_dirs_arg,
        comment_mapping_file,
        log_file,
        pruned_folder
    ]
    if base_reference_dir:
        php_pruner_cmd.append(base_reference_dir)

    try:
        subprocess.run(php_pruner_cmd, check=True)
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Error executing PHP Block Pruner: {e}")


def _run_javascript_pruner(target_folders_list, log_file, comment_mapping_file, pruned_folder, base_reference_dir=None):
    """Specific logic for executing JavaScript Block Pruner."""
    print("Executing JavaScript Block Pruner...")
    js_pruner_script_path = str(
        PROJECT_ROOT / "multilingual" / "javascript" / "block-pruner" / "BlockPruner.js")
    source_dirs_arg = ";".join(target_folders_list)

    js_pruner_cmd = [
        "node",
        js_pruner_script_path,
        source_dirs_arg,
        comment_mapping_file,
        log_file,
        pruned_folder
    ]
    if base_reference_dir:
        js_pruner_cmd.append(base_reference_dir)

    try:
        subprocess.run(js_pruner_cmd, check=True)
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Error executing JavaScript Block Pruner: {e}")


def _cbm_query(project_name, abs_path, cypher):
    """Execute a single Cypher query, return (columns, rows)."""
    args = json.dumps({"project": project_name, "query": cypher})
    cmd = ["codebase-memory-mcp", "cli", "query_graph", args, "--path", abs_path]
    r = subprocess.run(cmd, capture_output=True, text=True, check=True)
    data = json.loads(r.stdout)
    return data.get("columns", []), data.get("rows", [])


def cleanup_stale_workspaces(project_keyword):
    cbm_root = os.path.expanduser(r"~\.cache\codebase-memory-mcp")
    if not os.path.isdir(cbm_root):
        return

    removed, failed = [], []
    for entry in os.listdir(cbm_root):
        full = os.path.join(cbm_root, entry)
        if not os.path.isdir(full):
            continue
        if project_keyword.lower() in entry.lower():
            try:
                shutil.rmtree(full)
                removed.append(entry)
            except Exception as e:
                failed.append((entry, str(e)))

    # Also clean up lock files in the root directory
    for pattern in ("*.lock", "*.wal", "*.shm", "*.db-journal"):
        for f in glob.glob(os.path.join(cbm_root, pattern)):
            try:
                os.remove(f)
            except Exception:
                pass

    if removed:
        print(f"[Cleanup] Removed {len(removed)} stale workspace(s):")
        for r in removed:
            print(f"   - {r}")
    if failed:
        print(f"[Cleanup] Could NOT remove {len(failed)} (likely locked by running MCP):")
        for name, err in failed:
            print(f"   - {name}: {err}")
        print("   -> Close Claude Desktop / Cursor / VSCode and try again.")


def _run_cbm_data_structuring(pruned_folder):
    print("Executing Unified Data Structuring via Codebase-Memory...")

    # 1. Check CLI
    try:
        subprocess.run(["codebase-memory-mcp", "--version"],
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        raise RuntimeError("codebase-memory-mcp CLI not installed. Run: npm install -g codebase-memory-mcp")

    # Check tree-sitter-languages dependency
    if not tree_sitter_languages:
        raise RuntimeError("tree-sitter-languages is not installed. Run: pip install tree-sitter-languages")

    abs_pruned_path = os.path.abspath(pruned_folder)

    # 2. Index
    cleanup_stale_workspaces("ai-powered-legacy-maintenance")
    print(f"Indexing repository at: {abs_pruned_path} ...")
    idx_args = json.dumps({"repo_path": abs_pruned_path})
    subprocess.run(["codebase-memory-mcp", "cli", "index_repository", idx_args],
                   check=True, capture_output=True, text=True)
    print("Indexing completed.")

    # 3. Auto-detect project name
    project_name = "C-TechLearning-ai-powered-legacy-maintenance-pruned"
    try:
        r = subprocess.run(["codebase-memory-mcp", "cli", "list_projects", "{}"],
                           capture_output=True, text=True, check=True)
        d = json.loads(r.stdout)
        projs = d.get("projects", d) if isinstance(d, dict) else d
        for p in (projs or []):
            n = p.get("name") if isinstance(p, dict) else p
            if "pruned" in str(n):
                project_name = n
                break
    except Exception as e:
        print(f"Warning: project name autodetect failed: {e}")
    print(f"Project: {project_name}")

    # 4. Query CALLS edges and node properties (including start_line)
    nodes_info = {}     # qualified_name -> {name, file, start_line, ...}
    edges = set()       # (caller_qn, callee_qn)

    multi_col_query = (
        "MATCH (a)-[:CALLS]->(b) "
        "RETURN a.qualified_name, a.name, a.file_path, a.start_line, "
        "b.qualified_name, b.name, b.file_path, b.start_line"
    )
    use_fallback = False
    try:
        cols, rows = _cbm_query(project_name, abs_pruned_path, multi_col_query)
        if not rows:
            use_fallback = True
        else:
            for row in rows:
                if len(row) < 8:
                    use_fallback = True
                    break
                a_qn, a_n, a_f, a_line, b_qn, b_n, b_f, b_line = row[:8]
                a_qn = a_qn or a_n
                b_qn = b_qn or b_n
                if not a_qn or not b_qn:
                    continue

                # Convert start_line to integer
                try:
                    a_line = int(a_line) if a_line is not None else 1
                except (ValueError, TypeError):
                    a_line = 1
                try:
                    b_line = int(b_line) if b_line is not None else 1
                except (ValueError, TypeError):
                    b_line = 1

                nodes_info.setdefault(a_qn, {"name": a_n, "qualified_name": a_qn, "file": a_f, "start_line": a_line})
                nodes_info.setdefault(b_qn, {"name": b_n, "qualified_name": b_qn, "file": b_f, "start_line": b_line})
                edges.add((a_qn, b_qn))
    except Exception as e:
        print(f"Multi-column query failed, falling back. Error: {e}")
        use_fallback = True

    print(f"Collected {len(nodes_info)} nodes, {len(edges)} CALLS edges.")

    # 5. Use tree-sitter to extract signature and body by qualified_name
    print("Extracting function bodies from source files using tree-sitter (qname-keyed)...")
    miss_count = 0
    miss_samples = []
    for qn, info in nodes_info.items():
        rel = info.get("file") or ""
        abs_file = os.path.join(abs_pruned_path, rel.replace("/", os.sep)) if rel else ""

        sig, body = "", ""
        if abs_file and os.path.isfile(abs_file):
            res = lookup_function(
                abs_file,
                qualified_name=info.get("qualified_name"),
                fallback_name=info.get("name"),
                hint_line=info.get("start_line"),
            )
            if res:
                sig = res["signature"]
                body = res["body"]
            else:
                miss_count += 1
                if len(miss_samples) < 5:
                    miss_samples.append(
                        f"{info.get('qualified_name') or info.get('name')} @ {abs_file}"
                    )

        info["signature"] = sig or info.get("name", "")
        info["body"] = body
        info["file"] = abs_file if abs_file and os.path.isfile(abs_file) else rel

    if miss_count:
        print(f"[WARN] {miss_count} function(s) could not be located in source files.")
        for s in miss_samples:
            print(f"   - {s}")
        if miss_count > len(miss_samples):
            print(f"   ... and {miss_count - len(miss_samples)} more.")

    # 6. Build adjacency list and in-degree
    adj = defaultdict(set)
    in_deg = defaultdict(int)
    for a, b in edges:
        if b not in adj[a]:
            adj[a].add(b)
            in_deg[b] += 1
            in_deg.setdefault(a, 0)
    for qn in nodes_info:
        in_deg.setdefault(qn, 0)

    # 7. DFS to build tree
    def build(node_qn, on_path):
        info = nodes_info.get(node_qn, {"name": node_qn, "signature": node_qn, "file": "", "body": ""})
        nd = {
            "name": info["name"],
            "signature": info.get("signature", info["name"]),
            "file": info.get("file", ""),
            "body": info.get("body", ""),
            "children": []
        }
        if node_qn in on_path:
            nd["note"] = "Circular reference detected"
            return nd
        on_path = on_path | {node_qn}
        for child in sorted(adj.get(node_qn, [])):
            nd["children"].append(build(child, on_path))
        return nd

    # 8. In-degree 0 = root (entry functions)
    roots = sorted([q for q, d in in_deg.items() if d == 0 and q in nodes_info])
    if not roots and nodes_info:
        roots = sorted(nodes_info.keys())

    forest = [build(r, set()) for r in roots]

    output = {
        "project": project_name,
        "total_nodes": len(nodes_info),
        "trees": forest
    }
    with open("final-output-calltree.json", "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    print(f"Saved -> final-output-calltree.json")
    print(f"Total functions: {len(nodes_info)}, Roots: {len(roots)}")


def main():
    parser = argparse.ArgumentParser(
        description="Processes the log files generated by tests and restores the source code using Codebase-Memory."
    )
    parser.add_argument(
        "--language",
        default="java",
        help="Target programming language (default: java)"
    )
    parser.add_argument(
        "--target-folders-file",
        default=".\\target-folders.txt",
        help="File containing target folder paths (one per line). Default: .\\target-folders.txt"
    )
    parser.add_argument(
        "--target-folders",
        nargs="+",
        help="One or more target folder paths. If specified, takes precedence over --target-folders-file."
    )
    parser.add_argument(
        "--log-file",
        required=True,
        help="Path to the deduplicated instrumentation log file"
    )
    parser.add_argument(
        "--comment-mapping-file",
        required=True,
        help="Path to the comment mapping file"
    )
    parser.add_argument(
        "--pruned-folder",
        default="pruned\\",
        help="Path to the pruned output folder (default: pruned\\)"
    )
    parser.add_argument(
        "--events-file",
        required=True,
        help="Path to the structured events output file"
    )
    parser.add_argument(
        "--event-dictionary-file",
        default="event_dictionary.txt",
        help="Path to the event dictionary output file (default: event_dictionary.txt)"
    )
    parser.add_argument(
        "--block-pruner-jar",
        default=None,
        help="Path to the Block Pruner jar (defaults to Java target path)"
    )
    parser.add_argument(
        "--base-reference-dir",
        default=None,
        help="Base directory to preserve relative directory structures"
    )

    args = parser.parse_args()

    try:
        process_logs(
            language=args.language,
            target_folders_file=args.target_folders_file,
            target_folders=args.target_folders,
            log_file=args.log_file,
            comment_mapping_file=args.comment_mapping_file,
            pruned_folder=args.pruned_folder,
            events_file=args.events_file,
            event_dictionary_file=args.event_dictionary_file,
            block_pruner_jar=args.block_pruner_jar,
            base_reference_dir=args.base_reference_dir,
        )
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()