#!/usr/bin/env python3
"""
Processes the log files generated by tests (pruning, data structuring) and restores the source code.
Now leverages Codebase-Memory (CBM) for high-performance, multi-language data structuring.
"""

import argparse
import os
import sys

from .log_processors.external_pruners import (
    run_java_pruner,
    run_python_pruner,
    run_php_pruner,
    run_javascript_pruner
)
from .log_processors.cbm_structurer import run_cbm_data_structuring


def process_logs(
    language="java",
    log_file=None,
    comment_mapping_file=None,
    events_file=None,
    target_folders_file=None,
    target_folders=None,
    pruned_folder="pruned\\",
    event_dictionary_file="event_dictionary.txt",
    block_pruner_jar=None,
    base_reference_dir=None,
):
    """
    Core logic for processing instrumentation logs.
    """
    # --- Resolve target folders ---
    if target_folders:
        target_folders_list = target_folders
        print(f"Using {len(target_folders_list)} target folder(s) from function argument.")
    else:
        target_folders_file = target_folders_file or ".\\target-folders.txt"
        if not os.path.isfile(target_folders_file):
            raise FileNotFoundError(f"Target folders file does not exist: {target_folders_file}")
        with open(target_folders_file, "r", encoding="utf-8") as f:
            lines = f.readlines()
        target_folders_list = [
            line.strip() for line in lines
            if line.strip() and not line.strip().startswith("#")
        ]
        if not target_folders_list:
            raise ValueError(f"No target folders found in file: {target_folders_file}")
        print(f"Loaded {len(target_folders_list)} target folder(s) from file: {target_folders_file}")

    # Validate each folder exists
    for folder in target_folders_list:
        if not os.path.isdir(folder):
            raise NotADirectoryError(f"Target folder does not exist: {folder}")
    print(f"Target folders: {', '.join(target_folders_list)}")

    # Verify critical input files
    if not log_file:
        raise ValueError("log_file parameter is required")
    if not os.path.isfile(log_file):
        raise FileNotFoundError(f"Log file does not exist: {log_file}")
    if not comment_mapping_file:
        raise ValueError("comment_mapping_file parameter is required")
    if not os.path.isfile(comment_mapping_file):
        raise FileNotFoundError(f"Comment mapping file does not exist: {comment_mapping_file}")
    if not events_file:
        raise ValueError("events_file parameter is required")

    # Print configuration summary
    print(f"Starting log processing and data structuring for language: {language}...")
    print(f"  TargetFolders:      {'; '.join(target_folders_list)}")
    print(f"  LogFile:            {log_file}")
    print(f"  CommentMappingFile: {comment_mapping_file}")
    print(f"  PrunedFolder:       {pruned_folder}")
    print(f"  EventsFile:         {events_file}")
    print(f"  EventDictionaryFile:{event_dictionary_file}")
    if base_reference_dir:
        print(f"  BaseReferenceDir:   {base_reference_dir}")

    # Step 1: Execute Block Pruner (Language-specific)
    lang_lower = language.lower()
    if lang_lower == "java":
        run_java_pruner(target_folders_list, log_file, comment_mapping_file,
                        pruned_folder, block_pruner_jar, base_reference_dir)
    elif lang_lower == "python":
        run_python_pruner(target_folders_list, log_file,
                          comment_mapping_file, pruned_folder, base_reference_dir)
    elif lang_lower == "php":
        run_php_pruner(target_folders_list, log_file,
                       comment_mapping_file, pruned_folder, base_reference_dir)
    elif lang_lower in ["javascript", "js"]:
        run_javascript_pruner(target_folders_list, log_file,
                              comment_mapping_file, pruned_folder, base_reference_dir)
    else:
        raise ValueError(f"Unsupported language: {language}")

    # Step 2: Unified Data Structuring using Codebase-Memory & Tree-sitter
    run_cbm_data_structuring(pruned_folder)

    print("Log processing, data structuring, and source code restoration completed successfully!")


def main():
    parser = argparse.ArgumentParser(
        description="Processes the log files generated by tests and restores the source code using Codebase-Memory."
    )
    parser.add_argument(
        "--language",
        default="java",
        help="Target programming language (default: java)"
    )
    parser.add_argument(
        "--target-folders-file",
        default=".\\target-folders.txt",
        help="File containing target folder paths (one per line). Default: .\\target-folders.txt"
    )
    parser.add_argument(
        "--target-folders",
        nargs="+",
        help="One or more target folder paths. If specified, takes precedence over --target-folders-file."
    )
    parser.add_argument(
        "--log-file",
        required=True,
        help="Path to the deduplicated instrumentation log file"
    )
    parser.add_argument(
        "--comment-mapping-file",
        required=True,
        help="Path to the comment mapping file"
    )
    parser.add_argument(
        "--pruned-folder",
        default="pruned\\",
        help="Path to the pruned output folder (default: pruned\\)"
    )
    parser.add_argument(
        "--events-file",
        required=True,
        help="Path to the structured events output file"
    )
    parser.add_argument(
        "--event-dictionary-file",
        default="event_dictionary.txt",
        help="Path to the event dictionary output file (default: event_dictionary.txt)"
    )
    parser.add_argument(
        "--block-pruner-jar",
        default=None,
        help="Path to the Block Pruner jar (defaults to Java target path)"
    )
    parser.add_argument(
        "--base-reference-dir",
        default=None,
        help="Base directory to preserve relative directory structures"
    )

    args = parser.parse_args()

    try:
        process_logs(
            language=args.language,
            target_folders_file=args.target_folders_file,
            target_folders=args.target_folders,
            log_file=args.log_file,
            comment_mapping_file=args.comment_mapping_file,
            pruned_folder=args.pruned_folder,
            events_file=args.events_file,
            event_dictionary_file=args.event_dictionary_file,
            block_pruner_jar=args.block_pruner_jar,
            base_reference_dir=args.base_reference_dir,
        )
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()