#!/usr/bin/env python3
"""
Processes the log files generated by tests (pruning, data structuring) and restores the source code.
Now leverages Codebase-Memory (CBM) for high-performance, multi-language data structuring.

Accepts absolute (or relative) paths for all input/output files.
Supports multiple target folders via a file or direct parameter.
"""

from collections import defaultdict
import argparse
import os, shutil, glob
import sys
import subprocess
import json
import re
from pathlib import Path

# Dynamically resolve the project root (one level up from 'engineering' folder)
PROJECT_ROOT = Path(__file__).resolve().parent.parent

# --- Tree-sitter Configuration for Multi-language Support ---
try:
    import tree_sitter_languages
except ImportError:
    # We will raise a runtime error if CBM data structuring is run and tree-sitter is missing.
    tree_sitter_languages = None

LANG_MAP = {
    ".php": ("php",    "function_definition", "method_declaration"),
    ".py":  ("python", "function_definition"),
    ".java":("java",   "method_declaration",  "constructor_declaration"),
    ".go":  ("go",     "function_declaration", "method_declaration"),
    ".js":  ("javascript", "function_declaration", "method_definition"),
    ".ts":  ("typescript", "function_declaration", "method_definition"),
}


def extract_body_and_signature(file_path, func_name, start_line):
    """
    Uses tree-sitter to locate the matched function/method node based on the start line.
    Returns a tuple: (signature, body_source_code)
    """
    if not tree_sitter_languages:
        return "", ""
        
    ext = os.path.splitext(file_path)[1].lower()
    if ext not in LANG_MAP:
        return "", ""
        
    lang_name, *node_types = LANG_MAP[ext]
    try:
        parser = tree_sitter_languages.get_parser(lang_name)
        with open(file_path, "rb") as f:
            src_bytes = f.read()
        tree = parser.parse(src_bytes)
    except Exception as e:
        print(f"Warning: Failed to parse {file_path} with tree-sitter: {e}")
        return "", ""

    matched_node = None

    # Walk the AST to find the node that matches the start line and name
    def walk(node):
        nonlocal matched_node
        if matched_node is not None:
            return
        
        # Check if node matches target types and start line (1-based index)
        if node.type in node_types and node.start_point[0] + 1 == start_line:
            # Confirm name identifier match
            for child in node.children:
                if child.type in ("name", "identifier", "field_identifier"):
                    name_str = src_bytes[child.start_byte:child.end_byte].decode("utf-8", errors="ignore")
                    if name_str == func_name:
                        matched_node = node
                        return
            # Fallback: if no explicit name node matched but the line matches, we can still accept it
            matched_node = node
            return

        for child in node.children:
            walk(child)

    walk(tree.root_node)

    if not matched_node:
        return "", ""

    # Extract full source code of the node
    full_code = src_bytes[matched_node.start_byte:matched_node.end_byte].decode("utf-8", errors="ignore")
    
    # Extract signature: find the body block and take everything before it, or fallback to the first line
    body_node = None
    for child in matched_node.children:
        if child.type in ("block", "compound_statement", "function_body"):
            body_node = child
            break
            
    if body_node:
        sig_bytes = src_bytes[matched_node.start_byte:body_node.start_byte]
        signature = sig_bytes.decode("utf-8", errors="ignore").strip()
        # If the block starts with '{', append it to the signature or format nicely
        if signature.endswith("="): # Python lambda/assignment fallback
            signature = signature.rstrip("=")
    else:
        # Fallback to the first line of the matched block
        signature = full_code.splitlines()[0] if full_code else func_name

    return signature.strip(), full_code


def process_logs(
    language="java",
    log_file=None,
    comment_mapping_file=None,
    events_file=None,
    target_folders_file=None,
    target_folders=None,
    pruned_folder="pruned\\",
    event_dictionary_file="event_dictionary.txt",
    block_pruner_jar=None,
    base_reference_dir=None,
):
    """
    Core logic for processing instrumentation logs.
    """
    # --- Resolve target folders ---
    if target_folders:
        target_folders_list = target_folders
        print(
            f"Using {len(target_folders_list)} target folder(s) from function argument.")
    else:
        target_folders_file = target_folders_file or ".\\target-folders.txt"
        if not os.path.isfile(target_folders_file):
            raise FileNotFoundError(
                f"Target folders file does not exist: {target_folders_file}")
        with open(target_folders_file, "r", encoding="utf-8") as f:
            lines = f.readlines()
        target_folders_list = [
            line.strip() for line in lines
            if line.strip() and not line.strip().startswith("#")
        ]
        if not target_folders_list:
            raise ValueError(
                f"No target folders found in file: {target_folders_file}")
        print(
            f"Loaded {len(target_folders_list)} target folder(s) from file: {target_folders_file}")

    # Validate each folder exists
    for folder in target_folders_list:
        if not os.path.isdir(folder):
            raise NotADirectoryError(f"Target folder does not exist: {folder}")
    print(f"Target folders: {', '.join(target_folders_list)}")

    # Verify critical input files
    if not log_file:
        raise ValueError("log_file parameter is required")
    if not os.path.isfile(log_file):
        raise FileNotFoundError(f"Log file does not exist: {log_file}")
    if not comment_mapping_file:
        raise ValueError("comment_mapping_file parameter is required")
    if not os.path.isfile(comment_mapping_file):
        raise FileNotFoundError(
            f"Comment mapping file does not exist: {comment_mapping_file}")
    if not events_file:
        raise ValueError("events_file parameter is required")

    # Print configuration summary
    print(
        f"Starting log processing and data structuring for language: {language}...")
    print(f"  TargetFolders:      {'; '.join(target_folders_list)}")
    print(f"  LogFile:            {log_file}")
    print(f"  CommentMappingFile: {comment_mapping_file}")
    print(f"  PrunedFolder:       {pruned_folder}")
    print(f"  EventsFile:         {events_file}")
    print(f"  EventDictionaryFile:{event_dictionary_file}")
    if base_reference_dir:
        print(f"  BaseReferenceDir:   {base_reference_dir}")

    # Step 1: Execute Block Pruner (Language-specific)
    if language == "java":
        _run_java_pruner(target_folders_list, log_file, comment_mapping_file,
                         pruned_folder, block_pruner_jar, base_reference_dir)
    elif language == "python":
        _run_python_pruner(target_folders_list, log_file,
                           comment_mapping_file, pruned_folder, base_reference_dir)
    elif language == "php":
        _run_php_pruner(target_folders_list, log_file,
                        comment_mapping_file, pruned_folder, base_reference_dir)
    elif language in ["javascript", "js"]:
        _run_javascript_pruner(target_folders_list, log_file,
                               comment_mapping_file, pruned_folder, base_reference_dir)
    else:
        raise ValueError(f"Unsupported language: {language}")

    # Step 2: Unified Data Structuring using Codebase-Memory & Tree-sitter
    _run_cbm_data_structuring(pruned_folder)

    print("Log processing, data structuring, and source code restoration completed successfully!")


def _run_java_pruner(target_folders_list, log_file, comment_mapping_file, pruned_folder, block_pruner_jar, base_reference_dir=None):
    """Specific logic for executing Java Block Pruner."""
    if not block_pruner_jar:
        block_pruner_jar = str(PROJECT_ROOT / "multilingual" / "java" /
                               "block-pruner" / "target" / "block-pruner-1.0-SNAPSHOT.jar")

    print("Checking Java environment variables...")
    java_home = os.environ.get("JAVA_HOME")
    if not java_home:
        raise EnvironmentError(
            "JAVA_HOME environment variable not configured. Please set JAVA_HOME."
        )
    env = os.environ.copy()
    env["PATH"] = os.path.join(java_home, "bin") + \
        os.pathsep + env.get("PATH", "")

    print("Executing Java Block Pruner...")
    source_dirs_arg = ";".join(target_folders_list)
    block_pruner_cmd = [
        "java", "-jar", block_pruner_jar,
        source_dirs_arg,
        comment_mapping_file,
        log_file,
        pruned_folder
    ]
    if base_reference_dir:
        block_pruner_cmd.append(base_reference_dir)

    try:
        subprocess.run(block_pruner_cmd, env=env, check=True)
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Error executing Block Pruner: {e}")


def _run_python_pruner(target_folders_list, log_file, comment_mapping_file, pruned_folder, base_reference_dir=None):
    """Specific logic for executing Python Block Pruner."""
    print("Executing Python Block Pruner...")
    # Stub for Python pruner (if implemented in future)
    print("[INFO] Python block pruner is currently a stub.")


def _run_php_pruner(target_folders_list, log_file, comment_mapping_file, pruned_folder, base_reference_dir=None):
    """Specific logic for executing PHP Block Pruner."""
    print("Executing PHP Block Pruner...")
    php_pruner_script_path = str(
        PROJECT_ROOT / "multilingual" / "php" / "block-pruner" / "BlockPruner.php")
    source_dirs_arg = ";".join(target_folders_list)

    php_pruner_cmd = [
        "php",
        php_pruner_script_path,
        source_dirs_arg,
        comment_mapping_file,
        log_file,
        pruned_folder
    ]
    if base_reference_dir:
        php_pruner_cmd.append(base_reference_dir)

    try:
        subprocess.run(php_pruner_cmd, check=True)
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Error executing PHP Block Pruner: {e}")


def _run_javascript_pruner(target_folders_list, log_file, comment_mapping_file, pruned_folder, base_reference_dir=None):
    """Specific logic for executing JavaScript Block Pruner."""
    print("Executing JavaScript Block Pruner...")
    js_pruner_script_path = str(
        PROJECT_ROOT / "multilingual" / "javascript" / "block-pruner" / "BlockPruner.js")
    source_dirs_arg = ";".join(target_folders_list)

    js_pruner_cmd = [
        "node",
        js_pruner_script_path,
        source_dirs_arg,
        comment_mapping_file,
        log_file,
        pruned_folder
    ]
    if base_reference_dir:
        js_pruner_cmd.append(base_reference_dir)

    try:
        subprocess.run(js_pruner_cmd, check=True)
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Error executing JavaScript Block Pruner: {e}")


def _cbm_query(project_name, abs_path, cypher):
    """单次执行 Cypher 查询，返回 (columns, rows)。"""
    args = json.dumps({"project": project_name, "query": cypher})
    cmd = ["codebase-memory-mcp", "cli", "query_graph", args, "--path", abs_path]
    r = subprocess.run(cmd, capture_output=True, text=True, check=True)
    data = json.loads(r.stdout)
    return data.get("columns", []), data.get("rows", [])


def cleanup_stale_workspaces(project_keyword):
    cbm_root = os.path.expanduser(r"~\.cache\codebase-memory-mcp")
    if not os.path.isdir(cbm_root):
        return
    
    removed, failed = [], []
    for entry in os.listdir(cbm_root):
        full = os.path.join(cbm_root, entry)
        if not os.path.isdir(full):
            continue
        if project_keyword.lower() in entry.lower():
            try:
                shutil.rmtree(full)
                removed.append(entry)
            except Exception as e:
                failed.append((entry, str(e)))
    
    # 顺手清根目录的锁文件
    for pattern in ("*.lock", "*.wal", "*.shm", "*.db-journal"):
        for f in glob.glob(os.path.join(cbm_root, pattern)):
            try:
                os.remove(f)
            except Exception:
                pass
    
    if removed:
        print(f"[Cleanup] Removed {len(removed)} stale workspace(s):")
        for r in removed:
            print(f"   - {r}")
    if failed:
        print(f"[Cleanup] Could NOT remove {len(failed)} (likely locked by running MCP):")
        for name, err in failed:
            print(f"   - {name}: {err}")
        print("   → Close Claude Desktop / Cursor / VSCode and try again.")
            
            
def _run_cbm_data_structuring(pruned_folder):
    print("Executing Unified Data Structuring via Codebase-Memory...")

    # 1. 检查 CLI
    try:
        subprocess.run(["codebase-memory-mcp", "--version"],
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        raise RuntimeError("codebase-memory-mcp CLI not installed. Run: npm install -g codebase-memory-mcp")

    # 检查 tree-sitter-languages 依赖
    if not tree_sitter_languages:
        raise RuntimeError("tree-sitter-languages is not installed. Run: pip install tree-sitter-languages")

    abs_pruned_path = os.path.abspath(pruned_folder)

    # 2. 索引
    cleanup_stale_workspaces("ai-powered-legacy-maintenance")
    print(f"Indexing repository at: {abs_pruned_path} ...")
    idx_args = json.dumps({"repo_path": abs_pruned_path})
    subprocess.run(["codebase-memory-mcp", "cli", "index_repository", idx_args],
                   check=True, capture_output=True, text=True)
    print("Indexing completed.")

    # 3. 自动找项目名
    project_name = "C-TechLearning-ai-powered-legacy-maintenance-pruned"
    try:
        r = subprocess.run(["codebase-memory-mcp", "cli", "list_projects", "{}"],
                           capture_output=True, text=True, check=True)
        d = json.loads(r.stdout)
        projs = d.get("projects", d) if isinstance(d, dict) else d
        for p in (projs or []):
            n = p.get("name") if isinstance(p, dict) else p
            if "pruned" in str(n):
                project_name = n
                break
    except Exception as e:
        print(f"Warning: project name autodetect failed: {e}")
    print(f"Project: {project_name}")

    # 4. 查 CALLS 边和节点属性（包含 start_line）
    nodes_info = {}     # qualified_name -> {name, file, start_line, ...}
    edges = set()       # (caller_qn, callee_qn)

    # 我们需要获取 a.start_line 和 b.start_line 属性
    multi_col_query = (
        "MATCH (a)-[:CALLS]->(b) "
        "RETURN a.qualified_name, a.name, a.file_path, a.start_line, "
        "b.qualified_name, b.name, b.file_path, b.start_line"
    )
    use_fallback = False
    try:
        cols, rows = _cbm_query(project_name, abs_pruned_path, multi_col_query)
        if not rows:
            use_fallback = True
        else:
            for row in rows:
                if len(row) < 8:
                    use_fallback = True
                    break
                a_qn, a_n, a_f, a_line, b_qn, b_n, b_f, b_line = row[:8]
                a_qn = a_qn or a_n
                b_qn = b_qn or b_n
                if not a_qn or not b_qn:
                    continue
                
                # 转换 start_line 为整数
                try:
                    a_line = int(a_line) if a_line is not None else 1
                except ValueError:
                    a_line = 1
                try:
                    b_line = int(b_line) if b_line is not None else 1
                except ValueError:
                    b_line = 1

                nodes_info.setdefault(a_qn, {"name": a_n, "qualified_name": a_qn, "file": a_f, "start_line": a_line})
                nodes_info.setdefault(b_qn, {"name": b_n, "qualified_name": b_qn, "file": b_f, "start_line": b_line})
                edges.add((a_qn, b_qn))
    except Exception as e:
        print(f"Multi-column query failed, falling back. Error: {e}")
        use_fallback = True


    print(f"Collected {len(nodes_info)} nodes, {len(edges)} CALLS edges.")

    # 5. 使用 tree-sitter 从源文件精确提取 signature 和 body
    print("Extracting function bodies from source files using tree-sitter...")
    for qn, info in nodes_info.items():
        rel = info.get("file") or ""
        abs_file = os.path.join(abs_pruned_path, rel.replace("/", os.sep)) if rel else ""
        
        sig, body = "", ""
        if abs_file and os.path.isfile(abs_file):
            sig, body = extract_body_and_signature(abs_file, info["name"], info.get("start_line", 1))
            
        info["signature"] = sig or info["name"]
        info["body"] = body
        info["file"] = abs_file if abs_file and os.path.isfile(abs_file) else rel

    # 6. 构建邻接表与入度
    adj = defaultdict(set)
    in_deg = defaultdict(int)
    for a, b in edges:
        if b not in adj[a]:
            adj[a].add(b)
            in_deg[b] += 1
            in_deg.setdefault(a, 0)
    for qn in nodes_info:
        in_deg.setdefault(qn, 0)

    # 7. DFS 建树
    def build(node_qn, on_path):
        info = nodes_info.get(node_qn, {"name": node_qn, "signature": node_qn, "file": "", "body": ""})
        nd = {
            "name": info["name"],
            "signature": info.get("signature", info["name"]),
            "file": info.get("file", ""),
            "body": info.get("body", ""),
            "children": []
        }
        if node_qn in on_path:
            nd["note"] = "Circular reference detected"
            return nd
        on_path = on_path | {node_qn}
        for child in sorted(adj.get(node_qn, [])):
            nd["children"].append(build(child, on_path))
        return nd

    # 8. 入度为 0 = 根（入口函数）
    roots = sorted([q for q, d in in_deg.items() if d == 0 and q in nodes_info])
    if not roots and nodes_info:
        roots = sorted(nodes_info.keys())

    forest = [build(r, set()) for r in roots]

    output = {
        "project": project_name,
        "total_nodes": len(nodes_info),
        "trees": forest
    }
    with open("final-output-calltree.json", "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    print(f"Saved → final-output-calltree.json")
    print(f"Total functions: {len(nodes_info)}, Roots: {len(roots)}")


def main():
    parser = argparse.ArgumentParser(
        description="Processes the log files generated by tests and restores the source code using Codebase-Memory."
    )
    parser.add_argument(
        "--language",
        default="java",
        help="Target programming language (default: java)"
    )
    parser.add_argument(
        "--target-folders-file",
        default=".\\target-folders.txt",
        help="File containing target folder paths (one per line). Default: .\\target-folders.txt"
    )
    parser.add_argument(
        "--target-folders",
        nargs="+",
        help="One or more target folder paths. If specified, takes precedence over --target-folders-file."
    )
    parser.add_argument(
        "--log-file",
        required=True,
        help="Path to the deduplicated instrumentation log file"
    )
    parser.add_argument(
        "--comment-mapping-file",
        required=True,
        help="Path to the comment mapping file"
    )
    parser.add_argument(
        "--pruned-folder",
        default="pruned\\",
        help="Path to the pruned output folder (default: pruned\\)"
    )
    parser.add_argument(
        "--events-file",
        required=True,
        help="Path to the structured events output file"
    )
    parser.add_argument(
        "--event-dictionary-file",
        default="event_dictionary.txt",
        help="Path to the event dictionary output file (default: event_dictionary.txt)"
    )
    parser.add_argument(
        "--block-pruner-jar",
        default=None,
        help="Path to the Block Pruner jar (defaults to Java target path)"
    )
    parser.add_argument(
        "--base-reference-dir",
        default=None,
        help="Base directory to preserve relative directory structures"
    )

    args = parser.parse_args()

    try:
        process_logs(
            language=args.language,
            target_folders_file=args.target_folders_file,
            target_folders=args.target_folders,
            log_file=args.log_file,
            comment_mapping_file=args.comment_mapping_file,
            pruned_folder=args.pruned_folder,
            events_file=args.events_file,
            event_dictionary_file=args.event_dictionary_file,
            block_pruner_jar=args.block_pruner_jar,
            base_reference_dir=args.base_reference_dir,
        )
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()